### ISSUE TITLE
How to retrieve and use ASCII Codes of Icons

### ISSUE THREAD

**Issue by Fabaderheld** [PMaxx-Gaming/ttgo-display#1]
Hy,

since you only see ```󰌗``` in the config, how to you get the ascii code and add them to the config?

thanks

Fabian

**Comment by PMaxx-Gaming** [comment]
Hi, I used this: https://pictogrammers.github.io/@mdi/font/6.5.95/

You can just copy/paste the icon you want, and use your browsers search tool to find it

**Comment by Fabaderheld** [comment]
Damn this was fast! Thanks
